import { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { useWorkflowStore } from '../store/workflowStore'

function formatCost(cost: number): string {
  if (cost === 0) return '$0.00'
  if (cost < 0.0001) return '<$0.0001'
  return `$${cost.toFixed(4)}`
}

export function ResultsScreen() {
  const {
    nodes, goal,
    runStartTime, runEndTime,
    currentRunUsage, history,
    setScreen, resetExecution, setWorkflow,
  } = useWorkflowStore()

  const usageList          = Object.values(currentRunUsage)
  const totalCost          = usageList.reduce((s, u) => s + u.cost, 0)
  const totalInputTokens   = usageList.reduce((s, u) => s + u.inputTokens, 0)
  const totalOutputTokens  = usageList.reduce((s, u) => s + u.outputTokens, 0)

  const [copied, setCopied] = useState(false)

  const elapsedSeconds =
    runStartTime && runEndTime
      ? Math.round((runEndTime - runStartTime) / 1000)
      : null

  const doneNodes    = nodes.filter((n) => n.data.status === 'done' && n.data.output)
  const skippedCount = nodes.filter((n) => n.data.status === 'skipped').length
  const totalDone    = nodes.filter((n) => n.data.status === 'done').length

  // The final output is the last completed node that produced text
  const finalNode   = doneNodes[doneNodes.length - 1]
  const finalOutput = finalNode?.data.output ?? ''

  async function handleCopy() {
    if (!finalOutput) return
    await navigator.clipboard.writeText(finalOutput)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleNewWorkflow() {
    setWorkflow([], [])
    resetExecution()
    setScreen('home')
  }

  return (
    <div className="h-screen bg-white flex flex-col">
      {/* ── Header ── */}
      <div className="h-[52px] border-b border-[#e2e8f0] bg-white flex items-center px-5 gap-3 flex-shrink-0">
        <button
          onClick={() => setScreen('builder')}
          className="px-3 py-1.5 rounded text-[12.5px] border border-[#e2e8f0] text-[#64748b] hover:border-[#94a3b8] hover:text-[#0f172a] transition-all">
          Back to Builder
        </button>

        <div className="flex items-center gap-2 ml-auto">
          <div className="w-5 h-5 bg-[#0f172a] rounded flex items-center justify-center text-white text-[9px] font-bold">A</div>
          <span className="text-[13px] font-semibold text-[#0f172a]">Results</span>
        </div>

        <button
          onClick={handleNewWorkflow}
          className="ml-auto px-4 py-1.5 rounded text-[13px] font-medium bg-[#0f172a] text-white hover:bg-[#1e293b] transition-colors">
          New Workflow
        </button>
      </div>

      {/* ── Body ── */}
      <div className="flex flex-1 overflow-hidden">

        {/* ── Main output ── */}
        <div className="flex-1 overflow-y-auto p-8 border-r border-[#e2e8f0]">
          {/* Success badge */}
          <div className="inline-flex items-center gap-2 rounded px-3 py-1.5 mb-5 text-[12px] font-semibold text-green-700 bg-green-50 border border-green-200">
            <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
            Completed{elapsedSeconds !== null ? ` in ${elapsedSeconds}s` : ' successfully'}
          </div>

          <h1 className="text-[22px] font-bold text-[#0f172a] mb-2 leading-[1.2]">
            {goal || 'Workflow Output'}
          </h1>

          {finalNode && (
            <p className="text-[12px] text-[#94a3b8] mb-6">
              Generated by{' '}
              <span className="text-[#64748b]">{finalNode.data.label}</span>
              {finalNode.data.model ? ` · ${finalNode.data.model}` : ''}
            </p>
          )}

          <div className="bg-[#f8fafc] border border-[#e2e8f0] rounded px-5 py-5 text-[14px] text-[#374151] leading-[1.8]">
            {finalOutput ? (
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  h1: ({ children }) => <h1 className="text-[22px] font-bold text-[#0f172a] mt-6 mb-3 first:mt-0">{children}</h1>,
                  h2: ({ children }) => <h2 className="text-[18px] font-bold text-[#0f172a] mt-5 mb-2">{children}</h2>,
                  h3: ({ children }) => <h3 className="text-[15px] font-semibold text-[#0f172a] mt-4 mb-1">{children}</h3>,
                  h4: ({ children }) => <h4 className="text-[14px] font-semibold text-[#334155] mt-3 mb-1">{children}</h4>,
                  p:  ({ children }) => <p className="mb-3 last:mb-0">{children}</p>,
                  ul: ({ children }) => <ul className="list-disc list-outside pl-5 mb-3 space-y-1">{children}</ul>,
                  ol: ({ children }) => <ol className="list-decimal list-outside pl-5 mb-3 space-y-1">{children}</ol>,
                  li: ({ children }) => <li className="leading-[1.7]">{children}</li>,
                  strong: ({ children }) => <strong className="font-semibold text-[#0f172a]">{children}</strong>,
                  hr: () => <hr className="my-4 border-[#e2e8f0]" />,
                  table: ({ children }) => (
                    <div className="overflow-x-auto mb-4">
                      <table className="w-full text-[13px] border-collapse border border-[#e2e8f0] rounded">{children}</table>
                    </div>
                  ),
                  th: ({ children }) => <th className="bg-[#f1f5f9] text-left px-3 py-2 font-semibold text-[#0f172a] border border-[#e2e8f0]">{children}</th>,
                  td: ({ children }) => <td className="px-3 py-2 border border-[#e2e8f0] text-[#374151]">{children}</td>,
                  code: ({ children }) => <code className="bg-[#f1f5f9] text-[#0f172a] px-1.5 py-0.5 rounded text-[13px] font-mono">{children}</code>,
                  pre: ({ children }) => <pre className="bg-[#0f172a] text-[#e2e8f0] p-4 rounded overflow-x-auto mb-3 text-[13px] font-mono leading-[1.6]">{children}</pre>,
                }}
              >
                {finalOutput}
              </ReactMarkdown>
            ) : (
              <span className="text-[#94a3b8] italic">No output generated.</span>
            )}
          </div>
        </div>

        {/* ── Right sidebar ── */}
        <div className="w-[280px] p-5 flex flex-col gap-3 flex-shrink-0 overflow-y-auto bg-[#f8fafc]">
          {/* Stats card */}
          <div className="bg-white border border-[#e2e8f0] rounded p-4">
            <div className="text-[10px] font-semibold text-[#94a3b8] uppercase tracking-[.07em] mb-3">
              Run Stats
            </div>
            {[
              { k: 'Total time', v: elapsedSeconds !== null ? `${elapsedSeconds}s` : '—' },
              { k: 'Nodes run',  v: `${totalDone} / ${nodes.length}` },
              { k: 'Skipped',    v: skippedCount > 0 ? `${skippedCount}` : 'none' },
              { k: 'Total cost', v: formatCost(totalCost) },
              { k: 'Tokens in',  v: totalInputTokens > 0 ? totalInputTokens.toLocaleString() : '—' },
              { k: 'Tokens out', v: totalOutputTokens > 0 ? totalOutputTokens.toLocaleString() : '—' },
            ].map(({ k, v }) => (
              <div key={k} className="flex justify-between items-center py-2 border-b border-[#f1f5f9] last:border-0 text-[13px]">
                <span className="text-[#94a3b8]">{k}</span>
                <span className="text-[#0f172a] font-semibold">{v}</span>
              </div>
            ))}
          </div>

          {/* Per-node cost breakdown */}
          {usageList.length > 0 && (
            <div className="bg-white border border-[#e2e8f0] rounded p-4">
              <div className="text-[10px] font-semibold text-[#94a3b8] uppercase tracking-[.07em] mb-3">
                Cost Breakdown
              </div>
              {usageList.map((u) => (
                <div key={u.nodeId} className="py-2 border-b border-[#f1f5f9] last:border-0">
                  <div className="flex justify-between items-center text-[13px]">
                    <span className="text-[#0f172a] font-medium truncate max-w-[140px]">{u.label}</span>
                    <span className="text-[#0f172a] font-semibold">{formatCost(u.cost)}</span>
                  </div>
                  <div className="text-[11px] text-[#94a3b8] mt-0.5">
                    {u.inputTokens.toLocaleString()} in · {u.outputTokens.toLocaleString()} out
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Session history */}
          {history.length > 0 && (
            <div className="bg-white border border-[#e2e8f0] rounded p-4">
              <div className="text-[10px] font-semibold text-[#94a3b8] uppercase tracking-[.07em] mb-3">
                Session History
              </div>
              {history.map((run) => (
                <div key={run.id} className="py-2 border-b border-[#f1f5f9] last:border-0">
                  <div className="flex justify-between items-center text-[12px]">
                    <span className="text-[#374151] truncate max-w-[160px]">{run.goal}</span>
                    <span className="text-[#64748b] font-medium">{formatCost(run.totalCost)}</span>
                  </div>
                  <div className="text-[11px] text-[#94a3b8] mt-0.5">
                    {run.nodes.length} node{run.nodes.length !== 1 ? 's' : ''} · {new Date(run.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Action buttons */}
          <button
            onClick={handleCopy}
            disabled={!finalOutput}
            className="w-full py-2.5 rounded text-[13px] font-medium border border-[#e2e8f0] text-[#64748b] hover:border-[#94a3b8] hover:text-[#0f172a] disabled:opacity-40 transition-all bg-white">
            {copied ? 'Copied!' : 'Copy Output'}
          </button>

          <button
            onClick={() => setScreen('builder')}
            className="w-full py-2.5 rounded text-[13px] font-semibold bg-[#0f172a] text-white hover:bg-[#1e293b] transition-colors">
            Edit Workflow
          </button>

          <button
            onClick={handleNewWorkflow}
            className="w-full py-2.5 rounded text-[13px] font-medium border border-[#e2e8f0] text-[#64748b] hover:border-[#94a3b8] hover:text-[#0f172a] transition-all bg-white">
            New Workflow
          </button>
        </div>
      </div>
    </div>
  )
}
