import { useState } from 'react'
import { useWorkflowStore } from '../store/workflowStore'

export function ResultsScreen() {
  const {
    nodes, goal,
    runStartTime, runEndTime,
    setScreen, resetExecution, setWorkflow,
  } = useWorkflowStore()

  const [copied, setCopied] = useState(false)

  const elapsedSeconds =
    runStartTime && runEndTime
      ? Math.round((runEndTime - runStartTime) / 1000)
      : null

  const doneNodes    = nodes.filter((n) => n.data.status === 'done' && n.data.output)
  const skippedCount = nodes.filter((n) => n.data.status === 'skipped').length
  const totalDone    = nodes.filter((n) => n.data.status === 'done').length

  // The final output is the last completed node that produced text
  const finalNode   = doneNodes[doneNodes.length - 1]
  const finalOutput = finalNode?.data.output ?? ''

  async function handleCopy() {
    if (!finalOutput) return
    await navigator.clipboard.writeText(finalOutput)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleNewWorkflow() {
    setWorkflow([], [])
    resetExecution()
    setScreen('home')
  }

  return (
    <div className="h-screen bg-white flex flex-col">
      {/* ── Header ── */}
      <div className="h-[52px] border-b border-[#e2e8f0] bg-white flex items-center px-5 gap-3 flex-shrink-0">
        <button
          onClick={() => setScreen('builder')}
          className="px-3 py-1.5 rounded text-[12.5px] border border-[#e2e8f0] text-[#64748b] hover:border-[#94a3b8] hover:text-[#0f172a] transition-all">
          Back to Builder
        </button>

        <div className="flex items-center gap-2 ml-auto">
          <div className="w-5 h-5 bg-[#0f172a] rounded flex items-center justify-center text-white text-[9px] font-bold">A</div>
          <span className="text-[13px] font-semibold text-[#0f172a]">Results</span>
        </div>

        <button
          onClick={handleNewWorkflow}
          className="ml-auto px-4 py-1.5 rounded text-[13px] font-medium bg-[#0f172a] text-white hover:bg-[#1e293b] transition-colors">
          New Workflow
        </button>
      </div>

      {/* ── Body ── */}
      <div className="flex flex-1 overflow-hidden">

        {/* ── Main output ── */}
        <div className="flex-1 overflow-y-auto p-8 border-r border-[#e2e8f0]">
          {/* Success badge */}
          <div className="inline-flex items-center gap-2 rounded px-3 py-1.5 mb-5 text-[12px] font-semibold text-green-700 bg-green-50 border border-green-200">
            <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
            Completed{elapsedSeconds !== null ? ` in ${elapsedSeconds}s` : ' successfully'}
          </div>

          <h1 className="text-[22px] font-bold text-[#0f172a] mb-2 leading-[1.2]">
            {goal || 'Workflow Output'}
          </h1>

          {finalNode && (
            <p className="text-[12px] text-[#94a3b8] mb-6">
              Generated by{' '}
              <span className="text-[#64748b]">{finalNode.data.label}</span>
              {finalNode.data.model ? ` · ${finalNode.data.model}` : ''}
            </p>
          )}

          <div className="bg-[#f8fafc] border border-[#e2e8f0] rounded px-5 py-5 text-[14px] text-[#374151] leading-[1.8] whitespace-pre-wrap">
            {finalOutput
              ? finalOutput
              : <span className="text-[#94a3b8] italic">No output generated.</span>
            }
          </div>
        </div>

        {/* ── Right sidebar ── */}
        <div className="w-[280px] p-5 flex flex-col gap-3 flex-shrink-0 overflow-y-auto bg-[#f8fafc]">
          {/* Stats card */}
          <div className="bg-white border border-[#e2e8f0] rounded p-4">
            <div className="text-[10px] font-semibold text-[#94a3b8] uppercase tracking-[.07em] mb-3">
              Run Stats
            </div>
            {[
              { k: 'Total time', v: elapsedSeconds !== null ? `${elapsedSeconds}s` : '—' },
              { k: 'Nodes run',  v: `${totalDone} / ${nodes.length}` },
              { k: 'Skipped',    v: skippedCount > 0 ? `${skippedCount}` : 'none' },
            ].map(({ k, v }) => (
              <div key={k} className="flex justify-between items-center py-2 border-b border-[#f1f5f9] last:border-0 text-[13px]">
                <span className="text-[#94a3b8]">{k}</span>
                <span className="text-[#0f172a] font-semibold">{v}</span>
              </div>
            ))}
          </div>

          {/* Action buttons */}
          <button
            onClick={handleCopy}
            disabled={!finalOutput}
            className="w-full py-2.5 rounded text-[13px] font-medium border border-[#e2e8f0] text-[#64748b] hover:border-[#94a3b8] hover:text-[#0f172a] disabled:opacity-40 transition-all bg-white">
            {copied ? 'Copied!' : 'Copy Output'}
          </button>

          <button
            onClick={() => setScreen('builder')}
            className="w-full py-2.5 rounded text-[13px] font-semibold bg-[#0f172a] text-white hover:bg-[#1e293b] transition-colors">
            Edit Workflow
          </button>

          <button
            onClick={handleNewWorkflow}
            className="w-full py-2.5 rounded text-[13px] font-medium border border-[#e2e8f0] text-[#64748b] hover:border-[#94a3b8] hover:text-[#0f172a] transition-all bg-white">
            New Workflow
          </button>
        </div>
      </div>
    </div>
  )
}
